// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtSnC3TQXk0t6NiMLnwe7x-at_VSy4aDI',
    appId: '1:64268472646:web:d6bac0b41009a39172d547',
    messagingSenderId: '64268472646',
    projectId: 'quickpour-merchants',
    authDomain: 'quickpour-merchants.firebaseapp.com',
    storageBucket: 'quickpour-merchants.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIOC8r214F6zolW07RsEKbz66D6BxvxEU',
    appId: '1:64268472646:android:300b92b02ddefbad72d547',
    messagingSenderId: '64268472646',
    projectId: 'quickpour-merchants',
    storageBucket: 'quickpour-merchants.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgrKUajkXwe7vxcQjeOaOyzbvki9jVYJI',
    appId: '1:64268472646:ios:c75479b26d08579672d547',
    messagingSenderId: '64268472646',
    projectId: 'quickpour-merchants',
    storageBucket: 'quickpour-merchants.firebasestorage.app',
    iosBundleId: 'com.example.quickpourmerchant',
  );
}
